name: zad1
on: 
  issues:
    types: [opened]
  label:
    types: [created]	
jobs:
  sample_action:
    runs-on: ubuntu-latest
    steps:
      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
      - name: Print trigger
        run: echo "Trigger - ${{ github.event_name}}, user - ${{ github.actor}}, date - $NOW"
